name: designthinkingplus
favicon: null
layout_spectrum: 0.74579
typography_spectrum: 0.61481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a7a7a7'
    - '#838383'
    - '#5f5f5f'
  brandStrength: 0.8329082427080721
  lightness: 0.7972970870323479
  saturation: 0.05735613661818206
  rhythmicContrast: 0.04234614036977291
purpose: []
